### ISSUE TITLE
BF.RESERVE with an error_rate >= 2 will create a very slow bloom filter

### ISSUE THREAD

**Issue by Deimos** [RedisLabsModules/rebloom#10]
This definitely isn't something that should come up "normally", but I happened across today when I accidentally put the arguments to `BF.RESERVE` in the wrong order. It might also be a possible error if someone misinterprets the documentation about what valid `error_rate` values should be (for example if they try to get a 5% false positive rate by passing `5` instead of `0.05`).

```
127.0.0.1:6379> BF.RESERVE broken_bloom 2 1000
OK

127.0.0.1:6379> BF.DEBUG broken_bloom
1) "size:0"
2) "bytes:256 bits:2048 hashes:4294967295 capacity:4294965877 size:0 ratio:2"

127.0.0.1:6379> BF.ADD broken_bloom test
(integer) 1
(16.83s)
```

So it gets set up with using 4 billion hashes, and takes an extremely long time to add any items. I'm sure anyone that does this will realize something is wrong very quickly, but it would probably be best to restrict error_rate to the `0.0 < error_rate < 1.0` range anyway. There are other strange behaviors possible by going outside that range like passing a negative error_rate, and rates from 1.0 up to (but not including) 2.0 have 0 hashes, so 100% false positive rate.

And thanks again for the quick fix on the other issue earlier today, everything seems to be working great now.

**Comment by mnunberg** [comment]
Fixed
