### ISSUE TITLE
Any advice about how to transfer a large bloom filter between machines?

### ISSUE THREAD

**Issue by Deimos** [RedisLabsModules/rebloom#12]
This isn't truly an issue with ReBloom itself, but I thought that you might have some advice about how to approach it. I feel like this will probably be a pretty common thing that people would like to do with bloom filters, so it might be worth thinking about some way to help support it.

As mentioned [in my other issue, I have a pretty large bloom filter (~320M items)](https://github.com/RedisLabsModules/rebloom/issues/9). My hope was to be able to build this bloom filter locally, then dump it to a file, transfer to the production server, and restore it there. This would avoid having to put all the source data on the production server and do  the work of loading it into the bloom filter there. It also means I could restore it immediately if I ever need to reset Redis, instead of needing to re-add all the data from scratch each time.

However, the issue I've run into is that Redis only seems to be able to dump/restore a maximum of 512MB, due to [the limits of the string data type](https://redis.io/topics/data-types#strings). Attempting to use the RESTORE command to load a dumped bloom filter larger than this just fails (silent failure with `redis-cli`, "Broken pipe" errors through client).

Do you have any advice for a method I could use to transfer a large bloom filter and restore it?

**Comment by mnunberg** [comment]
You should be able to do this with AoF, but I think in this situation AoF just uses dump/restore anyway. I may need to add some more stuff to the module in order to support what you’re trying to do.

**Comment by dvirsky** [comment]
Why not dump to rdb and load on the target machine?

**Comment by Deimos** [comment]
Can you dump/load a single key through RDB without losing all of the other data that's already on the target machine, or only replace the entire database?

**Comment by dvirsky** [comment]
oh, in that case RDB won't help.

**Comment by Deimos** [comment]
Yeah, unfortunately that's pretty much the choice I was struggling with. Using RDB seems like it will work, but there's no way (at least that I've been able to find) to be "selective" about it and only replace a single key, so I'd have to do something like run a second instance of Redis solely for the bloom filter so it's safe to replace.

`RESTORE` seems to be the intended way to replace only one key and leave the rest intact, but the 512MB limit prevents it from working for a bloom filter this large.

**Comment by dvirsky** [comment]
@mnunberg we can maybe create an iterative dump function for this? might be useful for inverted indexes as well if we're ever going to move to the nokeys pattern..

@Deimos there is an rdb tool that might help you filter what you need, I'm not sure about the modules support in it currently. I know that the rdb format was changed recently to avoid having the rdb tool load the module into it. 

However, this is also the healthiest usage pattern for large redis data, especially with modules. And if you're doing this with RDB, you might as well just use replication, which is RDB under the hood.

**Comment by mnunberg** [comment]
@dvirsky I'm thinking in this case of implementing special commands which would incrementally transfer the contents of the bit fields - this would be useful for both AoF as well as using directly.

What I have in mind is:

(1) Determine from `INFO` how many different `slices` are going to be required. For simplicity's sake, we would start from the first filter and gradually populate it, so something like:

```
BF._DUMPHEADER
# Outputs
(array)
(array) - (errorRate, totalSize)
(array) - (numBytes, bpe, options, size)
(array) - (numBytes, bpe, options, size)
etc.
```

Then, you might do something like:

```
BF._LOADHEADER KEY ERROR
BF._ADDFILTER KEY ERROR OPTIONS
BF._DUMPFILTER KEY IDX BYTE_BEGIN BYTE_END
BF._FILLFILTER KEY IDX BYTE_BEGIN BYTE_END
```

The basic idea is that you'd get the meta information from the `DUMPHEADER` command, and you'd populate the filter from the given ranges.

Now this is admittedly low level, and we could write a script to handle it, but it does provide a relatively clean way of transferring the data, _assuming nothing else touches the filter while this takes place_.

I don't see how this transfers well to term indexes though

**Comment by dvirsky** [comment]
@mnunberg consider going with the SCAN pattern - you call one command, it returns some stuff and an identifier number to call it again. While that identifier is not 0 we call the command again with the same key name and iterator id, until it's 0. 

i.e:
```
> BF.SCANDUMP myFilter 0
1) 1456 //that's the iterator
2) "3847n30r8f13-e78fm§-8e7dm13-e6d3e-631e-8d7y1m3e-8d7y13e9d" // that's the data
> BF.SCANDUMP myFilter 1456
1) 3436
2) "asdfasdfasd3r23224..."
```

and on the other end:
```
> BF.LOADCHUNK myFilter 1456 "3847n30r8f13-e78fm§-8e7...."
1) OK
```

and so on. Let the magic happen internally (for example the next iterator offset can be encoded into the dump for verification, and we reject anything that's not the next iteration). from the user's POV they just need to call the iterative dump function several times and then the iterative load function.

**Comment by mnunberg** [comment]
Yeah, that's a much better approach!

**Comment by dvirsky** [comment]
the only problem would be "welding" back the parts into a consistent filter.

**Comment by mnunberg** [comment]
Yeah, that wouldn't be problematic afaik - as long as the process isn't interrupted etc. - but we're talking about a fairly manual migration anyway. And in any event, if the migration is interrupted we would end up with a filter that's empty - but hopefully nothing that will crash.

**Comment by mnunberg** [comment]
@Deimos - I've added two commands in the spirit of what @dvirsky outlined above. You can use this in a manner similar to:

https://github.com/RedisLabsModules/rebloom/blob/chunked-save/tests/pytests.py#L90-L108

**Comment by Deimos** [comment]
@mnunberg That looks great, thanks very much for working on this so quickly even though it's a pretty non-essential function.

For my case at least, it's definitely something I'm doing totally manually so I won't need to worry about the filter being modified during the dumping process. As long as I can dump to a file (or files) and then transfer and load them back in on a different redis server, that should be perfect.

**Comment by dvirsky** [comment]
@mnunberg we can mark the filter internally as read-only while we are generating its chunks, something like git rebase, then we can add an abort to the iterator, so things remain safe. e.g. `BF.DUMPABORT {key} {iter}`. Better yet have a refcount of active iterators. Then of course you need to "expire" the refs and oh my god it's getting so complex, let's leave it for now :)

**Comment by mnunberg** [comment]
There’s actually nothing inherently ‘dangerous’ about modifying the filter while it’s being read/written to - only the understanding that results may be inconsistent.

At worst, the filter remains partially initialized and there’s some memory wasted until it’s actually deleted.

**Comment by mnunberg** [comment]
@Deimos How's rebloom working out for you so far?

**Comment by Deimos** [comment]
Hey @mnunberg, thanks for asking. I'm not using it in anything that's actually in production yet, so my experience probably isn't very meaningful.

It's worked very well in my dev/testing though. Loading and updating the bloom filter is extremely fast using redis-cli's `--pipe` mode, and I haven't had any issues or surprises using it so far.

**Comment by mnunberg** [comment]
Hey @Deimos any news yet? we're gonna be adding a cuckoo filter API soon as well :) (already in Master).

**Comment by Deimos** [comment]
Unfortunately nothing exciting still, it's still working great for me in development though. Adding a cuckoo filter is interesting, are you considering renaming the module or anything as part of that?

**Comment by viktorvsk** [comment]
Hey, has anything changed recently?
