### ISSUE TITLE
Add client libraries

### ISSUE THREAD

**Issue by adrpino** [RedisLabsModules/rebloom#14]
It will be very useful to have client libraries like [RediSearch](https://github.com/RedisLabsModules/RediSearch#client-libraries).

I understand that this module is not as mature as Redisearch, but I could help with the Python client following [redisearch-py](https://github.com/RedisLabs/redisearch-py).

**Comment by mnunberg** [comment]
I'd be happy to make a client repository for this, and you would be able to contribute.

**Comment by mnunberg** [comment]
https://github.com/RedisLabs/rebloom-py

This is currently WIP, but I'm closing the issue here.

**Comment by avram** [comment]
There is a Java client mentioned in the docs-- but I don't see it anywhere. Does it exist?

**Comment by mnunberg** [comment]
https://github.com/RedisLabs/JReBloom
