### ISSUE TITLE
Counting?

### ISSUE THREAD

**Issue by zidsi** [RedisLabsModules/rebloom#16]
Just wondering if counting bloom (n-bit counter per bucket) ~~or even [Cuckoo filter](http://delivery.acm.org/10.1145/2680000/2674994/p75-fan.pdf?ip=194.0.191.102&id=2674994&acc=OA&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E11FD0E54F300593A&CFID=816662295&CFTOKEN=49520141&__acm__=1507907321_b3e025cc9a0d1f1b4952c9d62d6c63b2)~~ is planned?

Option to specify number of bits to use per bucket (default is 1) and thus enable counts if/when needed (knowing of course it will increase storage requirements) might not be too much out of the scope.

If it's not planned LUA workaround with n additional BFs is option as well...

BTW: Great work!

EDIT: Ups... missed existing [Cockoo filter](https://github.com/kristoff-it/redis-cuckoofilter) module. And for some use cases [countminsketch module ](https://github.com/RedisLabsModules/countminsketch) might fit as well.

**Comment by amiraliakbari** [comment]
The `redis-cuckoofilter` seems interesting. Adding it to the benchmark in [the introduction blog post](https://redislabs.com/blog/rebloom-bloom-filter-datatype-redis/) is useful. Also I suggest adding a benchmark section to rebloom.io site.

**Comment by dvirsky** [comment]
There is also an old counting bloom filter module we made (that had some performance issues). But we've decided to focus on making the straightforward bloom filter use case as robust as possible, and a new counting implementation is not on the roadmap ATM.
