### ISSUE TITLE
No key / no error?

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/rebloom#19]
Currently if you do something like this:

```
> DEL somekey
(interger) 1
> BF.MEXISTS somekey one two three
(error) ERR not found
```

So, logically, if the bloom filter is not yet created, these items will not be in it. In the app code, I usually just search for 'not found' in the error, but it's an extra conditional. Would it be possible to have an alternate `BF.EXISTS`/`BF.MEXISTS` command that returns `0` even if the key is nonexistent? It would make writing code against it more consistent. Example:

```
> DEL somekey
(interger) 1
> BF.XMEXISTS somekey one two three
1) (integer) 0
2) (integer) 0
3) (integer) 0
```

**Comment by dvirsky** [comment]
This is a good idea, and more in line with redis behavior. However, we are already at 1.0 with a few active users, it's not cool to change the protocol. 

@mnunberg what do you think? Nip it in the bud or forever hold our peace?

**Comment by stockholmux** [comment]
I actually don't think you should change it (because of compatibility) - just throw in two more commands that behave this way. ` BF.XMEXISTS`/`BF.XEXISTS` perhaps.

**Comment by casidiablo** [comment]
I think it would make sense to just return 0 instead of returning an error. For single checks, it might be OK to add conditionals to check for the error, but for pipelines, it gets hairier. Especially if you are using a redis client (say Jedis), where an ERR translates to an exception.

**Comment by mnunberg** [comment]
Merged
