### ISSUE TITLE
BF.ADD + Reserve

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/rebloom#23]
It's awesome that BF.ADD doesn't trigger an error for an empty filter using default sizes, however, there are scenarios where you want to create a filter with different parameters. I see two possibilities:

```
BF.RESERVENX key error_rate size
```
Reserve a new instance only if it doesn't already exist. If it does exist, just noop.

OR

```
BF.ADD RESERVE key error_rate size item
```
If creating a new Bloom filter, reserve it with the specified parameters. After reserved, add `item`

**Comment by mnunberg** [comment]
I'm leaning towards the second form, except something like `BF.ADD key RESERVE {...}` this way one can use `RESERVE` as a key :)

**Comment by stockholmux** [comment]
@mnunberg Does`BF.MADD` provide any complexity advantage or is it largely just for convenience over a `MULTI`/`BF.ADD`/`EXEC`?  E.g.
```
BF.MADD key item1 item2 item3
```
vs
```
MULTI
BF.ADD key item1
BF.ADD key item2
BF.ADD key item3
EXEC
```
Because you know if there is a reserve feature on `BF.ADD` someone will ask for it on `BF.MADD` eventually. That puts the `RESERVE` at the end thing in jeopardy then (as it would be an item on `BF.MADD`). If it's just convenience then it's easy to redirect to a `MULTI` / `BF.ADD` / `EXEC`.

**Comment by mnunberg** [comment]
I don’t intend on doing RESERVE with MADD. MADD does help for network optimization, but not much else for the time being.

**Comment by stockholmux** [comment]
cool. `RESERVE` at the end of `BF.ADD` makes a lot of sense then.

**Comment by mnunberg** [comment]
This functionality has been added in master. This may change prior to a release
