### ISSUE TITLE
How to scale?

### ISSUE THREAD

**Issue by ivalexa** [RedisLabsModules/rebloom#27]
Is it possible to utilize redis cluster mode to scale rebloom? otherwise the single redis node will handle all requests and create a bottleneck.

**Comment by dvirsky** [comment]
You can split the filter into multiple filters, each on a different cluster node, based on some criteria. For example if you want to deduplicate the ads that a user has seen, make the user id the partitioning key, and then the cluster will spread the filters across the nodes.

But a single filter cannot be split, and it's a pretty bad idea to do that. If you have a speed bottleneck on a single filter - then a. you are in a good place as it can withstand hundreds of thousands of requests per second, so if you have a server that needs to handle such loads, you have a very successful business! :) and b. just add slaves of the node and query them to get more performance.

**Comment by ivalexa** [comment]
Thanks
