### ISSUE TITLE
redis-rebloom docker container will not start

### ISSUE THREAD

**Issue by gnomff** [RedisLabsModules/rebloom#37]
`docker run -it -p 6379:6379 redislabs/rebloom:latest` gives the following error:

> 1:C 07 May 15:47:52.309 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 May 15:47:52.309 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 May 15:47:52.309 # Configuration loaded
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

> 1:M 07 May 15:47:52.311 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 07 May 15:47:52.311 # Server initialized
1:M 07 May 15:47:52.311 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 07 May 15:47:52.311 # Module /var/lib/redis/modules/rebloom.so failed to load: /var/lib/redis/modules/rebloom.so: cannot open shared object file: No such file or directory
1:M 07 May 15:47:52.311 # Can't load module from /var/lib/redis/modules/rebloom.so: server aborting

Docker verison: `Version 18.03.0-ce-mac60 (23751)`

**Comment by mnunberg** [comment]
Fixed

**Comment by gnomff** [comment]
Issue is not resolved with new image, please re-open

**Comment by mnunberg** [comment]
ok, now it should really work :)

```
mnunberg@mpb15iii ~/Source/rebloom $ docker run -it -p 6379:6379 redislabs/rebloom:latest
1:C 07 May 18:06:38.911 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 May 18:06:38.911 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 May 18:06:38.911 # Configuration loaded
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 4.0.8 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 07 May 18:06:38.913 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 07 May 18:06:38.913 # Server initialized
1:M 07 May 18:06:38.913 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 07 May 18:06:38.913 * Module 'bf' loaded from /var/lib/redis/modules/rebloom.so
1:M 07 May 18:06:38.913 * Ready to accept connections
^C1:signal-handler (1525716403) Received SIGINT scheduling shutdown...
1:M 07 May 18:06:43.353 # User requested shutdown...
1:M 07 May 18:06:43.354 # Redis is now ready to exit, bye bye...
```

**Comment by gnomff** [comment]
:+1:
