### ISSUE TITLE
latest build not working

### ISSUE THREAD

**Issue by cainiaocome** [RedisLabsModules/rebloom#39]
when docker run

1:M 17 May 07:06:03.064 # Module /var/lib/redis/modules/rebloom.so failed to load: /var/lib/redis/modules/rebloom.so: c
annot open shared object file: No such file or directory
1:M 17 May 07:06:03.064 # Can't load module from /var/lib/redis/modules/rebloom.so: server aborting

**Comment by cainiaocome** [comment]
checked the source, should be Dockerfile problem.

the ENV and CMD specified different path.

**Comment by joyang1** [comment]
@itamarhaber 
7213:M 05 Jul 2019 15:57:57.691 # Module redisbloom.so failed to load: dlopen(redisbloom.so, 6): image not found
7213:M 05 Jul 2019 15:57:57.691 # Can't load module from redisbloom.so: server aborting
