### ISSUE TITLE
where is redis.conf?

### ISSUE THREAD

**Issue by Loliko-Kai** [RedisLabsModules/rebloom#53]
can i use -v /data:/data ?
I want to find redis.conf

**Comment by mnunberg** [comment]
This is more a docker/general redis question. The config file shoudln't need to be modified at all; and yes, you can use an external volume, and you might be able to append extra arguments after the docker command line.

**Comment by giraffe-tree** [comment]
you can do like this

```
$ ls /local/dir/path/
redis.conf
```

```
docker run -p 6379:6379 -v /local/dir/path:/data --name redisbloom redislabs/rebloom:2.0.3 \
redis-server /data/redis.conf --loadmodule /usr/lib/redis/modules/redisbloom.so
```
