### ISSUE TITLE
Overflow problem

### ISSUE THREAD

**Issue by mendab1e** [RedisLabsModules/rebloom#8]
I got a strange behaviour when number of items in a filter reached the reserved capacity: a new filter is chained but I can't add any items there. `BF.ADD` command always returns 0 for any key, debug info shows that this filter has size=1
```
BF.DEBUG my_bloom
1) "size:112022461"
2) "bytes:268435456 bits:2147483648 hashes:14 capacity:112022460 size:112022460 ratio:0.0001"
3) "bytes:1073741824 bits:8589934592 hashes:16 capacity:389468927 size:1 ratio:2.5e-05"
```
It is also can be reproduced with commit [54effb245a5f78c2111bfe91b892dffc7718f980](https://github.com/RedisLabsModules/rebloom/commit/54effb245a5f78c2111bfe91b892dffc7718f980)

**Comment by mnunberg** [comment]
That fix only partially fixed the issue. Try the latest master for a fix.

**Comment by mendab1e** [comment]
With the last commit `BF.ADD` works like a charm, but something wrong with a size counting on chained filter. I can add keys there, but the size isn't increased.
```
127.0.0.1:6379> BF.DEBUG my_bloom
1) "size:112022461"
2) "bytes:268435456 bits:2147483648 hashes:14 capacity:112022460 size:112022460 ratio:0.0001"
3) "bytes:1073741824 bits:8589934592 hashes:16 capacity:389468927 size:1 ratio:2.5e-05"
127.0.0.1:6379> BF.ADD my_bloom testkey1
(integer) 1
127.0.0.1:6379> BF.DEBUG my_bloom
1) "size:112022461"
2) "bytes:268435456 bits:2147483648 hashes:14 capacity:112022460 size:112022460 ratio:0.0001"
3) "bytes:1073741824 bits:8589934592 hashes:16 capacity:389468927 size:1 ratio:2.5e-05"
```

**Comment by mendab1e** [comment]
Sorry, just noticed that I've used wrong bloom filter name, still can't add anything to the chained filter even with the latest commit.

**Comment by mnunberg** [comment]
I've pushed some more commits to help resolve this issue, though I think it should still work with yesterday's version as well.

I've also added a test case replicating your environment. This should help.

I'm assuming you're using a 64 bit platform - is this correct?

**Comment by mendab1e** [comment]
Thanks for the fix, It works with the latest commit for me.
