### ISSUE TITLE
Large bloom filters seem to return 100% false positives

### ISSUE THREAD

**Issue by Deimos** [RedisLabsModules/rebloom#9]
I'm trying to use ReBloom to create a bloom filter for checking user passwords against [the 300M+ breached password hashes that Troy Hunt released recently](https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/).

However, it seems like using it for a bloom filter with this many items does not work, and just results in a filter that says it has a size of 1, returns `1` for all `BF.EXISTS` checks, and fails to add anything after the first item. I try to create a bloom filter with an expected size of 350,000,000 items (a bit of room to grow with further updates) and 0.01 error rate:

```
127.0.0.1:6379> BF.RESERVE breached 0.01 350000000
OK

127.0.0.1:6379> BF.ADD breached asdf
(integer) 1

127.0.0.1:6379> BF.ADD breached somethingelse
(integer) 0

127.0.0.1:6379> BF.MADD breached a s d f
1) (integer) 0
2) (integer) 0
3) (integer) 0
4) (integer) 0

127.0.0.1:6379> BF.debug breached
1) "size:1"
2) "bytes:536870912 bits:4294967296 hashes:7 capacity:448089842 size:1 ratio:0.01"

127.0.0.1:6379> BF.EXISTS breached anything
(integer) 1

127.0.0.1:6379> BF.EXISTS breached ididntaddthis
(integer) 1
```

**Comment by mnunberg** [comment]
There were some issues with large bloom filters, but those should be fixed by now. Are you using master, or are you running off an older version?

**Comment by Deimos** [comment]
I'm using master, cloned from github earlier today.

**Comment by mnunberg** [comment]
Fixed. Thanks for the report!

**Comment by Deimos** [comment]
Pulled down the fix and it looks good so far, thanks very much for the incredibly fast fix.

I'll proceed with adding the actual hashes to it and let you know if I run into anything else.
